# Generated by Django 5.0 on 2024-10-01 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(default='default/default_restaurante.png', upload_to='restaurante/')),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(default='default/default_plato.png', upload_to='platos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/platos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ingrediente', models.TextField(blank=True, null=True)),
                ('instruccion', models.TextField(blank=True, null=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_gastronomico.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='EventoGastronomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(default='default/default_evento.png', upload_to='eventos/')),
                ('restaurante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t_gastronomico.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tnombre', models.CharField(max_length=100)),
                ('Tapellido', models.CharField(max_length=100)),
                ('Tcorreo', models.EmailField(max_length=254)),
                ('Tcelular', models.CharField(max_length=10)),
                ('Tfoto', models.ImageField(default='default/default_turista.png', upload_to='turista/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(null=True)),
                ('comentario', models.TextField(null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_gastronomico.plato')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_gastronomico.restaurante')),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_gastronomico.turista')),
            ],
        ),
    ]
