# Generated by Django 5.0 on 2024-10-12 15:29

import t_gastronomico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_gastronomico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventogastronomico',
            name='foto',
            field=models.ImageField(default='default/default_evento.png', upload_to=t_gastronomico.models.generar_ruta_foto_evento),
        ),
        migrations.AlterField(
            model_name='plato',
            name='foto',
            field=models.ImageField(default='default/default_plato.png', upload_to=t_gastronomico.models.generar_ruta_foto),
        ),
        migrations.AlterField(
            model_name='plato',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=t_gastronomico.models.generar_ruta_video),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='foto',
            field=models.ImageField(default='default/default_restaurante.png', upload_to=t_gastronomico.models.generar_ruta_foto_restaurante),
        ),
        migrations.AlterField(
            model_name='turista',
            name='Tfoto',
            field=models.ImageField(default='default/default_turista.png', upload_to=t_gastronomico.models.generar_ruta_foto_turista),
        ),
    ]
